Repository valora-inc/dapp-list, pull requests merged in 2022-02, with the labels that each got.

#38 Add Celo Tracker to the Dapp list
  assets/celo-tracker.png
  locales/base.json
  src/valora-dapp-list.json
Labels: bakeoff

#48 ImmortalDAO Finance Submission for Valora Bakeoff
  assets/immortaldao-finance.png
  locales/base.json
  src/valora-dapp-list.json
Labels: bakeoff, status: accepted

#73 Submit Flywallet for bakeoff 👏🏾
  assets/flywallet.png
  locales/base.json
  src/valora-dapp-list.json
Labels: bakeoff, status: accepted

#100 Add Pinnata to Dapp-List
  assets/pinnata.png
  locales/base.json
  src/valora-dapp-list.json
Labels: bakeoff, status: in review

#110 Add swap bitssa for Valora bakeoff
  assets/swapbitssa.png
  locales/base.json
  src/valora-dapp-list.json
Labels: bakeoff, status: in review

#119 Add Trelis Pay
  assets/trelispay.png
  locales/base.json
  locales/en.json
  src/valora-dapp-list.json
Labels: bakeoff, status: accepted

#105 Add Chispend to BakeOff
  assets/chimoney-chispend.png
  locales/base.json
  src/valora-dapp-list.json
Labels: bakeoff, status: accepted
